---
title: "Shaoqian_Chen_HW5"
author: "Shaoqian Chen"
date: "4/13/2020"
output: html_document
---

#Question 1
```{r}
library(cluster)
df1 = read.csv("universities.csv",header = TRUE) 
head(df1)
```

```{r}
rownames(df1)=df1$University
df1 = df1[-c(1)]
head(df1)
```

##  a)
```{r}
m1=prcomp(df1, scale=T)
names(m1)
summary(m1)
m1$rotation
```

```{r}
m1$x
```

```{r}
biplot(m1,scale=0,cex=0.6)
grid()
```

```{r}
#mirror image
m1$rotation=-m1$rotation
m1$x=-m1$x
biplot(m1, scale=0,cex=0.6)
#abline(0,slope1)
grid()

#
rot=m1$rotation
slope1=rot[1,2]/rot[1,1]
slope1
abline(0,slope1)
```
### *The Pricipal Components are shown above, From this biplot we can identify the clusters of universities*


##  b)
```{r}

df2 = df1[,c('SAT','Top10','Accept','SFRatio','Expenses','Grad')] 
df = dist(df2)
length(df)
head(df)
```

```{r}
dd = as.matrix(df)
dim(dd)
```

```{r}
# daisy() to find distances even if columns are not numeric #
df2 = daisy(df1)
class(df2)
as.matrix(df2)[1:25,1:25]
```
### *Euclidian distances between all pairs of universities are shown above*


```{r}
#complete linkage
seg.hc = hclust(df2,method='complete') 
plot(seg.hc,cex=0.4)
#
# cut at h=0.5 
abline(h=0.5,col='red',lty=2) 
cut(as.dendrogram(seg.hc),h=0.5)
# identigy the clusters 
rect.hclust(seg.hc,k=4)
```

```{r}
#single linkage
seg.hc = hclust(df2,method='single') 
plot(seg.hc,cex=0.4)
#
# cut at h=0.5 
abline(h=0.5,col='red',lty=2) 
cut(as.dendrogram(seg.hc),h=0.5)
rect.hclust(seg.hc,k=4)
```

## c)
```{r}
set.seed(2)
bb = c(-8,8)
km.out = kmeans(df1,4,nstart=20)
km.out
```

```{r}
colors = km.out$cluster
plot(m1$x[,1],m1$x[,2],col=colors,pch=20,ylim=bb,xlim=bb,main='K-means with K=4 cluster
s')
```



# Question 2
```{r}
d2 = read.csv("brands.csv",header = TRUE)
dim(d2)
head(d2)
```

```{r}
rownames(d2) = d2[,1]
d22 = d2[-c(1,2)]
head(d22)
```

```{r}
m2=prcomp(d22, scale=T)
m2
```

```{r}
summary(m2)
```

```{r}
m2$rotation
```

```{r}
m2$x
```
### *Principle components are show above*

```{r}
library(devtools)
#install_github("vqv/ggbiplot")
library(ggbiplot)
ggbiplot(m2,obs.scale = 1,var.scale =1, groups = d2$Manuf,ellipse = TRUE, circle = TRUE) + scale_color_discrete(name = '')+theme(legend.direction ='vertical',legend.position ='right')
```


```{r}
df2 = daisy(df2)
class(d22)
head(d22)
as.matrix(d22)[1:43,1:43]
```

```{r}
#complete linkage
seg.hc = hclust(d22,method='complete') 
plot(seg.hc,cex=0.4)
#
# cut at h=0.5 
abline(h=0.5,col='red',lty=2) 
cut(as.dendrogram(seg.hc),h=0.5)
```

```{r}
# identigy the clusters 
rect.hclust(seg.hc,k=4)
```

```{r}
#single linkage
seg.hc2 = hclust(dd2,method='single') 
plot(seg.hc2,cex=0.4)
#
# cut at h=0.5 
abline(h=0.5,col='red',lty=2) 
cut(as.dendrogram(seg.hc2),h=0.5)
```

```{r}
# identigy the clusters 
rect.hclust(seg.hc2,k=4)
```

```{r}
complete = cutree(seg.hc, k=4)
single = cutree(seg.hc2, k=4)
data.frame(complete, single)
```

```{r}
km.out = kmeans(df2,4,nstart=20)
km.out
```

```{r}
kmeans = km.out$cluster
df2_c = data.frame(complete,single,kmeans)
df2_c
```

```{r}
c1 = complete
c2 = single
c3 = kmeans
plot(m2$x[,1], m2$x[,2], col=c1, pch=20, ylim=bb,xlim=bb, xlab="PC1", ylab="PC2",main='complete linkage with K=4 clusters')
```



```{r}
plot(m2$x[,1], m2$x[,2], col=c2, pch=20, ylim=bb,xlim=bb, xlab="PC1", ylab="PC2",main='single linkage with K=4 clusters')
```

```{r}
plot(m2$x[,1], m2$x[,2], col=c3, pch=20, ylim=bb,xlim=bb, xlab="PC1", ylab="PC2",main='kmeans with K=4 clusters')
```


```{r}
par(mfcol=c(1,3))
plot(m2$x[,1], m2$x[,2], col=c1, pch=20, ylim=bb,xlim=bb, xlab="PC1", ylab="PC2",main='complete linkage with K=4 clusters')
plot(m2$x[,1], m2$x[,2], col=c2, pch=20, ylim=bb,xlim=bb, xlab="PC1", ylab="PC2",main='single linkage with K=4 clusters')
plot(m2$x[,1], m2$x[,2], col=c3, pch=20, ylim=bb,xlim=bb, xlab="PC1", ylab="PC2",main='kmeans with K=4 clusters')
```

```{r}
df2_c
```
### **
